# Generated by Django 5.0.1 on 2024-02-18 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('residential_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(default='someone@someone.com', max_length=254)),
                ('land_location', models.CharField(max_length=255)),
                ('X1_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('Y1_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('X2_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('Y2_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('X3_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('Y3_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('X4_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('Y4_point', models.DecimalField(decimal_places=15, max_digits=20)),
                ('land_type', models.CharField(max_length=50)),
                ('landmark', models.TextField()),
                ('LGA', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('size_of_land', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
