# Generated by Django 5.0.1 on 2024-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landproperty',
            name='email',
            field=models.EmailField(default='Someone@tonek.com', max_length=254),
        ),
        migrations.AddField(
            model_name='landproperty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
