# Generated by Django 5.0.1 on 2024-02-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='address',
            field=models.CharField(default='default_address', max_length=255),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
